version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    hostname: keycloak
    ports:
      - '8080:8080'
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://ep-late-cloud-a1qog1c7.ap-southeast-1.aws.neon.tech/keycloak?sslmode=require
      - KC_DB_USERNAME=default
      - KC_DB_PASSWORD=6V1OocaldpND
      - KC_KEYCLOAK_ADMIN=admin
      - KC_KEYCLOAK_ADMIN_PASSWORD=change_me
    command: ['start-dev']
    networks:
      - express_service_topdev

networks:
  express_service_topdev:
    external:
      name: express_service_topdev
